### ISSUE TITLE
Dash example video doesn't work on Safari 9

### ISSUE THREAD

**Issue by mimcz** [videojs/videojs-contrib-dash#22] opened 2015-10-02 11:10 UTC
Hi, the example videojs dash doesn't work on Safari 9. I was doing some compatibility tests and I tryed the example page http://videojs.github.io/videojs-contrib-dash/ and it doesn't work well on Safari 9 (OSX 10.11). Can it be connected with some specific codec compatibility for Safari? Console does not throw any errors and it looks like it loads the content and starts playing ok. Time is also updatig, but there is only sound and no picture and it gets stucked after seek. I tryed different source on my implementation and it worked ok.

**Comment by richardbushell** [comment] 2015-10-26 19:40
Yep, I confirm, our examples work on PC (all OSs and all browsers we've tested), plus Mac (Chrome) but Mac El-Capitan with Safari 9 is a problem. We do get playback, but Seek breaks things! When seeking we often get the Poster re-appear (without Play Button overlay) and then we carry on hearing the audio only.

**Comment by sprice** [comment] 2015-10-31 05:38
This seems to be a problem upstream. 

Visit the dash.js test site at http://dashif.org/reference/players/javascript/v1.5.1/samples/dash-if-reference-player/index.html and enter the manifest `http://rdmedia.bbc.co.uk/dash/ondemand/testcard/1/client_manifest-events.mpd`

The test player plays audio but no video.

**Comment by sprice** [comment] 2015-10-31 06:09
So now I think it's a media issue. Some of the content on http://dash-mse-test.appspot.com/media.html will play in Safari.

**Comment by richardbushell** [comment] 2015-10-31 10:47
Hi Shawn
As I said, we *DO* get DASH playback in Mac El-Capitan with Safari 9 (so I think it is happy with our MP4 and codecs), but SEEK breaks things! When seeking we often get the Poster re-appear (without the Big Play Button overlay) and then we carry on hearing the audio only. So, I think this issue is related to VJS interaction with Safari on SEEKING. For some reason we get the the Poster re-appear. We carry on hearing the audio. I assume that the video is also continuing to play fine BUT behind the poster???

**Comment by sprice** [comment] 2015-11-01 09:19
I updated [my test case](https://gist.github.com/sprice/86c598719d715328f692) to include a poster. 

I can confirm I have now begun to experience the poster showing up sometimes when seeking in Safari 9 (though I don't see the big play button).

**Comment by richardbushell** [comment] 2015-11-01 11:53
Yes, I confirm, we get the Poster and not the big play button. I'm guessing the video is continuing to play behind the poster as we can still hear the audio.

**Comment by richardbushell** [comment] 2015-11-01 11:57
Here's our test case:
https://www.handpickedhotels.co.uk/fawsleyhall/welcome/video-photos/watch-our-video

**Comment by sprice** [comment] 2015-11-02 07:36
It seems the issue is with the `<video>` `poster` attribute, and not the poster div that videojs creates. In a pinch `$(player.el()).find('video').removeAttr('poster');` will stop the poster issues with Safari, though finding the root cause is ideal.

**Comment by richardbushell** [comment] 2015-11-02 09:59
Our implementation for clients requires a Poster that appears initially and when ended, so we can't just remove the Poster unfortunately. Yes, finding the root cause and a fix is imperative, but it's beyond our understanding of videojs and Safari interaction to know what is causing the problem.

**Comment by sprice** [comment] 2015-11-26 07:32
Looks like the poster issue is an upstream problem. I've opened an issue [on the dash.js repo](https://github.com/Dash-Industry-Forum/dash.js/issues/907)

**Comment by forbesjo** [comment] 2016-02-18 21:44
It looks like the dash.js issue above was closed due to this issue being a Safari bug, if there's no more information we will close this issue.

**Closed** 2016-03-25 17:14 UTC
Labels: needs: more information

**Comment by vsalema** [comment] 2022-09-22 14:19
[https://filmsgratos.com/image/player.jpg](url)

**Comment by vsalema** [comment] 2023-01-08 12:53
solution
https://codepen.io/vsalema/pen/xxJxWxQ
