### ISSUE TITLE
Player not refreshing live source manifest

### ISSUE THREAD

**Issue by Palethorn** [videojs/videojs-contrib-dash#81] opened 2016-05-11 06:37 UTC
There is an issue with a live source. Player is not refreshing manifest when using this plugin on videojs. Player plays for a while until it runs out of first batch of chunks, then it stops. I've tested the source using dashjs reference player and it works correctly.
This live example is still running for debugging purposes with dashjs 2.1.1 and videojs-dash 2.3.0: http://player.cavar.pw/videojs/
Issue was also present on videojs-dash version 2.2.0.
You can use this stream as a reference: http://coder01.spectar.tv:1935/live/_definst_/colorbars/manifest.mpd
It's coming from wowza version 4.4.1.

**EDIT**
I updated the test urls since the streams stopped working on https

**Comment by Palethorn** [comment] 2016-05-13 08:33
It seems that when videojs is handling autoplay ManifestUpdated::onPlaybackStarted is never invoked, and as a result, manifest refresh timer is never initialized. This is happening because videojs is invoking play() on video element instead on the tech and PLAYBACK_STARTED event is never fired.
I changed this line

`  Html5.prototype.play = function play() {
    this.el_.play();
  };`

to this:
`  Html5.prototype.play = function play() {
      this.techCall_("play");
  };`
in videojs lib. This is probably not the correct way to do this.

**Comment by theleon** [comment] 2016-11-18 11:06
Hi, any updates on that?

**Comment by forbesjo** [comment] 2017-03-02 19:51
Digging into if this is an issue when using a source element vs `player.src()` with autoplay

**Comment by featheast** [comment] 2017-05-30 00:29
We are having the exact same issue at the moment, and yes we are using autoplay in the <video> tag and using player.src() to load the mpd file.
It seems to be working fine if put the mpd source in <source> tag.

**Comment by Sewci0** [comment] 2017-08-29 08:23
I had the same issue. I don't know if it will be helpful but running player.play() with a 1sec delay seams to solve the issue.

**Comment by pettersamuelsen** [comment] 2017-11-17 16:18
I had the same problem, but I solved it by calling `play()` inside of the `canplay` event:

```
this.player.on('canplay', () => {
  this.play();
});
```

**Comment by pavelhoral** [comment] 2018-05-29 10:12
The issue is that with `autoplay: true` the playback is started right away after the `src()` is called. However `Html5Dash` registers event handlers only after the timestamp request is handled. This leaves Dash.js uninitialized.

**Comment by squarebracket** [comment] 2018-06-07 16:17
Is this still a bug? I'm unable to reproduce with the latest version and [this dash.js test feed](https://vm2.dashif.org/livesim/mup_30/testpic_2s/Manifest.mpd), but it's possible my test setup is different.

**Comment by pavelhoral** [comment] 2018-06-08 08:28
Still happens on dashjs 2.7.0 and video.js 6.10.1 (I don't have vjs 7 in my setup) and videojs-contrib-dash 2.9.3.

**Comment by pavelhoral** [comment] 2018-06-08 09:32
I am no longer able to reproduce with the latest version.

http://plnkr.co/edit/i9ZZggGzfqpoN1mIBaCg?p=preview

**Comment by squarebracket** [comment] 2018-06-09 00:04
Do you mean that there's no spinner before the video starts playing? Feel free to open an issue for that if you think it's appropriate.

In any case, since this specific issue (manifest not being requesting) is no longer an issue, I'm going to close this issue. If anyone finds this issue persists for them with the latest version, feel free to reopen this.

**Closed by squarebracket** 2018-06-09 00:04 UTC
Labels: bug
